### ISSUE TITLE
Error starting dev server with @cloudflare/vite-plugin v1.19.0

### ISSUE THREAD

**Issue by m-sureshraj** [cloudflare/workers-sdk#11765]
### What versions & operating system are you using?

```
System:
    OS: macOS 15.6.1
    CPU: (8) arm64 Apple M1
    Memory: 333.19 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.20.0
    npm: 10.9.3
    pnpm: 10.26.2
    Deno: 1.43.1
  npmPackages:
    @cloudflare/vite-plugin: ^1.19.0 => 1.19.0
    wrangler: ^4.54.0 => 4.54.0
```

### Please provide a link to a minimal reproduction

-

### Describe the Bug

The dev command failed to start the dev server due to an unmet peer dependency.

```
Error: The installed version of Wrangler (4.54.0) does not satisfy the peer dependency required by @cloudflare/vite-plugin (^4.56.0).
Please install wrangler@^4.56.0.
```

The latest version of the plugin (v1.19.0) lists "wrangler": "^4.56.0" as a peer dependency. However, Wrangler v4.56.0 has been marked as [deprecated](https://socket.dev/npm/package/wrangler/overview/4.56.0).

<img width="1325" height="376" alt="Image" src="https://github.com/user-attachments/assets/45632a44-3405-45b6-9c16-9e6b5ddd1414" />

### Please provide any relevant error logs

```
failed to load config from /Users/foo/Desktop/cf-worker/movies/vite.config.ts
error when starting dev server:
Error: The installed version of Wrangler (4.54.0) does not satisfy the peer dependency required by @cloudflare/vite-plugin (^4.56.0).
Please install wrangler@^4.56.0.
    at assertWranglerVersion (file:///Users/foo/Desktop/cf-worker/movies/node_modules/.pnpm/@cloudflare+vite-plugin@1.19.0_vite@7.3.0_@types+node@25.0.3_jiti@2.6.1__workerd@1.20251210.0_wrangler@4.54.0/node_modules/@cloudflare/vite-plugin/dist/index.mjs:1492:77)
    at async file:///Users/foo/Desktop/cf-worker/movies/node_modules/.pnpm/@cloudflare+vite-plugin@1.19.0_vite@7.3.0_@types+node@25.0.3_jiti@2.6.1__workerd@1.20251210.0_wrangler@4.54.0/node_modules/@cloudflare/vite-plugin/dist/index.mjs:17732:1
```

**Comment by jackall3n** [comment]
Quick 'fix' is to install `@cloudflare/vite-plugin@1.71.1`

The issue is simply that the latest `wrangler` workspace package has not been published to NPM yet.

**Comment by m-sureshraj** [comment]
> Quick 'fix' is to install @cloudflare/vite-plugin@1.71.1

Yes, that's how I resolved the issue for now. 👍

**Comment by petebacondarwin** [comment]
I'll change the latest dist-tag perhaps...

**Comment by petebacondarwin** [comment]
I have marked the "latest" version of vite-plugin at 1.17.1, so installing it should now work.
We'll release new versions of all these packages in January that will fix things up further.

**Comment by ilkin0** [comment]
even with the **vite-plugin 1.17.1,** i still face the same issue. dev gives an error:
`Error: There is a new version of the pre-bundle for "/node_modules/.vite/deps_ssr/sonner.js?v=bd9dc871", a page reload is going to ask for it.
    at CustomModuleRunner.cachedModule (workers/runner-worker.js:1264:20)
    ... 8 lines matching cause stack trace ...
    at CustomModuleRunner.cachedRequest (workers/runner-worker.js:1143:73) {
  cause: Error: There is a new version of the pre-bundle for "node_modules/.vite/deps_ssr/sonner.js?v=bd9dc871", a page reload is going to ask for it.
      at CustomModuleRunner.cachedModule (workers/runner-worker.js:1264:20)
      at request (workers/runner-worker.js:1182:83)
      at /src/routes/__root.tsx:6:31
      at Object.runInlinedModule (workers/runner-worker.js:1365:4)
      at CustomModuleRunner.directRequest (workers/runner-worker.js:1236:59)
      at CustomModuleRunner.cachedRequest (workers/runner-worker.js:1143:73)
      at /src/routeTree.gen.ts:2:31
      at Object.runInlinedModule (workers/runner-worker.js:1365:4)
      at CustomModuleRunner.directRequest (workers/runner-worker.js:1236:59)
      at CustomModuleRunner.cachedRequest (workers/runner-worker.js:1143:73) {                                                                                 remote: true
  },
  status: 500,                                                                                                                                               statusText: undefined,
  headers: undefined,
  data: undefined,
  body: undefined,
  unhandled: true
}`

vite.config.ts:
`import { defineConfig } from "vite";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import { cloudflare } from "@cloudflare/vite-plugin";
import viteReact from "@vitejs/plugin-react";
import viteTsConfigPaths from "vite-tsconfig-paths";
import tailwindcss from "@tailwindcss/vite";

export default defineConfig({
  server: {
    port: 3000,
  },
  plugins: [
    viteTsConfigPaths({
      projects: ["./tsconfig.json"],
    }),
    cloudflare({ viteEnvironment: { name: "ssr" } }),
    tanstackStart(),
    viteReact(),
    tailwindcss(),
  ],
});`

package.json:
`
"dev": "vite dev --port 3000",
"preview": "vite build && vite preview"

"devDependencies": {
    "@cloudflare/vite-plugin": "1.17.1",
   "wrangler": "^4.56.0",
}
`

**Comment by m-sureshraj** [comment]
@ilkin0, I had encountered this error before, and rerunning the dev script fixed it.

**Comment by jamesopstad** [comment]
@ilkin0 This isn't the same issue as the error is different to the one described. Please could you open a new issue with a reproduction for your issue? Thanks.

**Comment by jamesopstad** [comment]
Closing as new versions of `wrangler` and `@cloudflare/vite-plugin` have now been released.

**Comment by ilkin0** [comment]
Sorry for the late response, the issue still is goning on with:
"wrangler": "^4.58.0"
"@cloudflare/vite-plugin": "^1.20.1" 
versions, @jamesopstad . 

i will open an issue regarding this bug
