### ISSUE TITLE
🐛 BUG: `wrangler dev --remote` no longer logs?

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/workers-sdk#4165]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.13.0

### What version of Node are you using?

18

### What operating system are you using?

Mac

### Describe the Bug

I cloned https://github.com/joshthoward/d1-tutorial/tree/main

Updated to wrangler 3.13.0, and now logs don't show up in the console when running `wrangler dev --remote`

Instead I see:
```
[wrangler:inf] GET /cdn-cgi/ProxyWorker/pause 204 No Content (3ms)
[wrangler:inf] GET /cdn-cgi/ProxyWorker/pause 204 No Content (0ms)
[wrangler:inf] GET /cdn-cgi/ProxyWorker/pause 204 No Content (1ms)
Total Upload: 3.03 KiB / gzip: 1.13 KiB
[wrangler:inf] GET /cdn-cgi/ProxyWorker/play 204 No Content (0ms)
✘ [ERROR] {

    message: 'Uncaught TypeError: Failed to establish the WebSocket connection: expected server to
  reply with HTTP status code 101 (switching protocols), but received 404 instead.',
    cause: {}
  }


[wrangler:inf] GET /cdn-cgi/ProxyWorker/pause 204 No Content (0ms)
```

### Please provide a link to a minimal reproduction

https://github.com/joshthoward/d1-tutorial/tree/main

**Comment by rozenmd** [comment]
I can confirm that downgrading to `3.12.0` shows logs as expected.

**Comment by admah** [comment]
@rozenmd thanks for filing this issue. We've identified some issues with the latest version of Wrangler (3.13.0) and are working on fixes. In the meantime, we recommend staying on Wrangler 3.12.0 (npm install wrangler@latest should point to 3.12.0).

**Comment by admah** [comment]
@rozenmd we have published a new version of Wrangler (3.13.1) that reverts the change that was causing issues. You should be able to update and see logs as expected.

**Comment by rozenmd** [comment]
cheers @admah

**Comment by penalosa** [comment]
Reopening this while we investigate the root cause

**Comment by RamIdeas** [comment]
This has been fixed in #4175. Since this bug is only present in that branch and not main, I will close this issue now. Thanks for reporting!

**Comment by timkelty** [comment]
I am still experiencing this today, using: `wrangler@3.110.0`. Works fine without the `--remote` flag.

**Comment by dev-itzarun** [comment]
Still Logs Not Working on ``` npx wrangler dev --remote ``` dev on version ```4.50.0```

And also D1 ```remote = true``` on wrangler.toml with sveltekit ``` npm i -D @sveltejs/adapter-cloudflare ``` not works
