### ISSUE TITLE
🐛 Bug Report — Runtime APIs: Get an incorrect Location param when using Response.redirect

### ISSUE THREAD

**Issue by h11g** [cloudflare/workers-sdk#5221]
When I use `wrangler dev --host localhost:3343` for local development, I want to get a redirect response. But my port number was mishandled and I can’t get the redirect address I’m hoping for. I'm sure it's not the browser's behavior.

wrangler version: `^3.32.0`

### Example

![image](https://github.com/cloudflare/workerd/assets/19600972/1dbdfebf-672f-43e8-88e0-f369387c76fd)

**Comment by jfnault-seedbox** [comment]
Im experimenting the same issue

From what I found, seem to have been introduced in 
https://github.com/cloudflare/workers-sdk/pull/4950

[packages/wrangler/templates/startDevWorker/ProxyWorker.ts](https://github.com/cloudflare/workers-sdk/pull/4950/files#diff-89724563c6547a3aa374c922a5449349cd00ee0fe6415382a1b9d404d8bd5911)
`
function rewriteUrlRelatedHeaders(headers: Headers, from: URL, to: URL) {
	headers.forEach((value, key) => {
		if (typeof value === "string" && value.includes(from.host)) {
			headers.set(
				key,
				value.replaceAll(from.origin, to.origin).replaceAll(from.host, to.host)
			);
		}
	});
}
`

I start the worker like this:
npx wrangler dev --env dev --assets assets --host devsite.localg --local-upstream devsite.localg:33667

devsite.localg:33667: is my origin, a node express server 

 --host devsite.localg: I access my worker from same domain devsite.localg:8787
 
 
 
 Behavior:
 Url: devsite.localg:8787/to-redirect
 
 with the script above is converted to:
 http://devsite.localg:8787:8787:8787/destination
 
 this is because of:
 value.replaceAll(from.origin, to.origin).replaceAll(from.host, to.host)
 
 there is the value I have for (from , to)
 
 {
  'from.origin': 'http://devsite.localg',
  'to.origin': 'devsite.localg:8787',
  'from.host': 'devsite.localg',
  'to.host': 'devsite.localg:8787'
}

"http://devsite.localg:8787/destination"
.replaceAll("devsite.localg", "devsite.localg:8787") 
.replaceAll("devsite.localg", "devsite.localg:8787")

**Comment by petebacondarwin** [comment]
Fixed by #4950.
@h11g and @jfnault-seedbox - please could you try out the beta version of Wrangler with:

```sh
npx https://prerelease-registry.devprod.cloudflare.dev/workers-sdk/runs/7843359492/npm-package-wrangler-4950 dev path/to/script.js
```

**Comment by mariusGundersen** [comment]
This has still not been fixed, more than a year later. It makes it impossible to test redirects in workers locally with a locally running upstream server.

**Comment by jfsiii** [comment]
This impacted us on Wrangler 4.x as well. I ended up using [`patch-package`](https://github.com/ds300/patch-package/) to alter `rewriteUrlRelatedHeaders` (thanks for the pointer, https://github.com/cloudflare/workers-sdk/issues/5221#issuecomment-1996147061).

My intial pass looked like this, roughly "do what you used to do, but if the result is an invalid URL, construct the URL bit-by-bit"

```
diff --git a/node_modules/wrangler/wrangler-dist/ProxyWorker.js b/node_modules/wrangler/wrangler-dist/ProxyWorker.js
index 8a78f24..755d157 100644
--- a/node_modules/wrangler/wrangler-dist/ProxyWorker.js
+++ b/node_modules/wrangler/wrangler-dist/ProxyWorker.js
@@ -215,10 +215,23 @@ function rewriteUrlRelatedHeaders(headers, from, to) {
   headers.delete("Set-Cookie");
   headers.forEach((value, key) => {
     if (typeof value === "string" && value.includes(from.host)) {
-      headers.set(
-        key,
-        value.replaceAll(from.origin, to.origin).replaceAll(from.host, to.host)
-      );
+      // patch because of: https://github.com/cloudflare/workers-sdk/issues/5221#issuecomment-1996147061
+      // first try the original way
+      let newValue = value.replaceAll(from.origin, to.origin).replaceAll(from.host, to.host)
+      // If the URL is malformed it'll parse to null
+      const parsed = URL.parse(newValue);
+      if (parsed === null) {
+        // Original attempt is malformed. Try to fix it by parsing it and reconstructing it.
+        const originalUrl = URL.parse(value);
+        if (originalUrl) {
+          originalUrl.protocol = to.protocol;
+          originalUrl.hostname = to.hostname;
+          originalUrl.port = to.port;
+          newValue = originalUrl.toString();
+        }
+      }
+      headers.set(key, newValue);
+      // end of patch
     }
   });
   for (const cookie of setCookie) {
```

That fixed the issue described here for us. However, it then hit another issue where the `origin` header was incorrect (missing the port), so we chose to early return from the function

```
diff --git a/node_modules/wrangler/wrangler-dist/ProxyWorker.js b/node_modules/wrangler/wrangler-dist/ProxyWorker.js
index 8a78f24..4ec9545 100644
--- a/node_modules/wrangler/wrangler-dist/ProxyWorker.js
+++ b/node_modules/wrangler/wrangler-dist/ProxyWorker.js
@@ -211,6 +211,10 @@ var liveReloadScript = `
 </script>
 `;
 function rewriteUrlRelatedHeaders(headers, from, to) {
+  // patch because of: https://github.com/cloudflare/workers-sdk/issues/5221
+  // and issues found in ISSUE_FOR_OUR_REPO
+  // in ^ this ^ case, the port was missing from the `origin` header during local development
+  return;
   const setCookie = headers.getAll("Set-Cookie");
   headers.delete("Set-Cookie");
   headers.forEach((value, key) => {
```
