### ISSUE TITLE
🐛 BUG: Duplicate printing of wrangler dev logs

### ISSUE THREAD

**Issue by joshthoward** [cloudflare/workers-sdk#6855]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

all

### What version of Node are you using?

v20.6.1

### What operating system and version are you using?

Mac Sonoma

### Observed behavior
Duplicate logs on state changes
```
⎔ Starting local server...
[wrangler:inf] Ready on http://localhost:59290
▲ [WARNING] Queues are currently in Beta and are not supported in wrangler dev remote mode.


⎔ Shutting down local server...
▲ [WARNING] Queues are currently in Beta and are not supported in wrangler dev remote mode.
```
or just (seemingly) randomly
```
▲ [WARNING] Queues are currently in Beta and are not supported in wrangler dev remote mode.


▲ [WARNING] Queues are currently in Beta and are not supported in wrangler dev remote mode.


▲ [WARNING] Queues are currently in Beta and are not supported in wrangler dev remote mode.
```
### Expected behavior
Single log per distinct warning.

### Steps to reproduce
Please provide the following:
- Attach a queue or a sqlite DO which are in beta to produce a warning. I have seen this with other warnings, so there might be an easier way.

**Comment by RamIdeas** [comment]
@penalosa and I found the cause of this yesterday

**Comment by emily-shen** [comment]
@penalosa and @RamIdeas, is this fixed by the --x-dev-env work?

**Comment by penalosa** [comment]
> @penalosa and @RamIdeas, is this fixed by the --x-dev-env work?

No, there's still an issue here—every time the Worker reloads we re-print these messages.
