### ISSUE TITLE
🐛 BUG: can not install wrangler@3.97.0

### ISSUE THREAD

**Issue by liuhanqu** [cloudflare/workers-sdk#7584]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.28.1

### What version of Node are you using?

22.12.0

### What operating system and version are you using?

Mac

### Describe the Bug

execute command
```
npm i wrangler

npm ERR! code ETARGET
npm ERR! notarget No matching version found for unenv-nightly@2.0.0-20241212-153011-af71c96.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

```
npm view unenv-nightly versions 
```
the last five version are 
```
...
'2.0.0-1726478054.1e87097',
'2.0.0-1726687684.061a2b7',
'2.0.0-20240919-125358-9a64854',
'2.0.0-20240924-181319-d5e42d9',
'2.0.0'
```

there is not matched version `unenv-nightly@2.0.0-20241212-153011-af71c96`

**Comment by liuhanqu** [comment]
you can try
```
npm install wrangler@latest
```
It's my fault, not 3.28.1.

**Comment by edmundhung** [comment]
Thanks for the issue! It should be resolved in [v3.98.0](https://github.com/cloudflare/workers-sdk/releases/tag/wrangler%403.98.0). If you’re still running into any problems, please let us know.

**Comment by liuhanqu** [comment]
v3.98.0 not work
![image](https://github.com/user-attachments/assets/2bba6ab9-942a-4213-8f6e-6a5354ba07b5)

**Comment by emily-shen** [comment]
Hey, I can't seem to reproduce this - `pnpm i wrangler@3.98.0` works for me. can i just double check this issue is still happening for you? what about 3.99.0?
