### ISSUE TITLE
🐛 BUG: Import an D1 exported DB cannot be imported in local - HashIndex detected hash table inconsistency

### ISSUE THREAD

**Issue by lakano** [cloudflare/workers-sdk#8153]
### Which Cloudflare product(s) does this pertain to?

D1

### What versions are you using?

3.108.0

### What operating system and version are you using?

Arch Linux

### Describe the Bug

Hi,

After an export of our D1 database on remote ( wrangler d1 export dbname --remote --output export.sql ), I'm trying to import it on local ( wrangler d1 execute --local --file export.sql ), but I got a lot of errors.

### Please provide any relevant error logs

```
kj/table.c++:57: error: HashIndex detected hash table inconsistency. This can happen if you create a kj::Table with a hash index and you modify the rows in the table post-indexing in a way that would change their hash. This is a serious bug which will lead to undefined behavior.
stack: ; kj::getStackTrace() = /workers/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2b4cc7d /workers/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2b4868c /workers/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2b4b0ab /workers/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2277fc0 /workers/node_modules/@cloudflare/workerd-linux-64/bin/workerd@39d1109 /workers/node_modules/@cloudflare/workerd-linux-64/bin/workerd@39d0edd /workers/node_modules/@cloudflare/workerd-linux-64/bin/workerd@38358f5

```

**Comment by mrankine** [comment]
I am also seeing this, after upgrading from 3.103. to 3.109.1.

**Comment by lakano** [comment]
Unfortunately I'm not allowed by the company. I'll try to find time to create a dumb requests of JSON fields with a lot of the content, and duplicate this query to reach the same massive SQL file, to see if I can reproduce it and then to attach it here to help you to debug. 
I'm pretty sure it's caused by some buffer / limit problems.

**Comment by emily-shen** [comment]
@mrankine I've just tried to execute that file and it seems to work fine without issues :( 

I'm testing with a clean new database, wondering if you're running this on a local db with stuff in it already, or if there are any other details of your setup that i might need to reproduce this?

**Comment by mrankine** [comment]
@emily-shen I created a [fresh project](https://github.com/mrankine/wrangler-8153) and fresh database and can reproduce the error.

My setup is Debian 12 bookworm running in WSL2 on Windows.
- `Linux *** 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 GNU/Linux`
- Windows 11 Home 24H2

Has wrangler picked up a new version of capnproto recently? Maybe something to do with [this commit](https://github.com/capnproto/capnproto/commit/3a63ccbbe4b58def33e2301f4e49b5b689cf0fed)?

Maybe @lakano has more clues?

**Comment by mrankine** [comment]
Just confirming that, in that repo, downgrading Wrangler to 3.103.2 resolves the error.

**Comment by petebacondarwin** [comment]
Hmm... so on MacOS 15.3.1:

```
pnpm wrangler d1 execute prod-d1-tutorial --local --file hash_errors.sql 

 ⛅️ wrangler 3.112.0 (update available 3.114.1)
---------------------------------------------------------

🌀 Executing on local database prod-d1-tutorial (e2f51fce-c9fe-408b-88f3-79bed5a07e01) from .wrangler/state/v3/d1:
🌀 To execute on your remote database, add a --remote flag to your wrangler command.
🚣 7155 commands executed successfully.
```

**Comment by mrankine** [comment]
Just confirming this is still an issue in Wrangler 4. Are you able to reproduce this on a Linux machine?

**Comment by petebacondarwin** [comment]
OK I have recreated it in our Windows CI: https://github.com/cloudflare/workers-sdk/actions/runs/13885240243/job/38849070736?pr=8513#step:5:3838

**Comment by lrapoport-cf** [comment]
hy @vy-ton , can someone on the d1 team please take a look at this?

**Comment by brewaa** [comment]
I can confirm that this is an issue for me also using Wrangler 4 with the latest version of `cloudflare@latest`.

I'm using:

npm create cloudflare@latest -- my-nuxt-app --framework=nuxt

I apply my migrations to my DB as usual , the schema is there as expected but running an SQL script that worked in previous versions results in the following errors (hundreds of):

```
kj/table.c++:57: error: HashIndex detected hash table inconsistency. This can happen if you create a kj::Table with a hash index and you modify the rows in the table post-indexing in a way that would change their hash. This is a serious bug which will lead to undefined behavior.
stack: ; kj::getStackTrace() = 7ff6584c7927 7ff65885f8c1 7ff65885abff 7ff65885e144 7ff657fe588e 7ff657ec32d0 7ff657ec302a 7ff657ec2e1a 7ff6598aac39 7ff6b98c90ba 12a00000010 12a00a97c80 9 12a00000760 12a17ff0568
```

Downgrading to Wrangler 3.103.2  does resolve the hash issue but if you scaffold a project using  `npm create cloudflare@latest`  which installs Wrangler 4 and the newer config changes after running `npm run cf-typegen`, the project will fail to build/preview properly because the file referenced in `.wrangler\deploy\config.json` does not exist (`{"configPath":"..\\..\\dist\\_worker.js\\wrangler.json"}`

This is the error after downgrade, the downgrade being required, because there is definitely a problem with Wrangler 4:

```
 There is a deploy configuration at ".wrangler\deploy\config.json".

  But the redirected configuration path it points to, "dist\_worker.js\wrangler.json", does not
  exist.
```

Hope that helps and someone can get eyes on this soon.

**Comment by arthurgailes** [comment]
Also having this problem with Windows, wrangler v4.5. downgrading resolved the issue.

**Comment by brewaa** [comment]
> Also having this problem with Windows, wrangler v4.5. downgrading resolved the issue.

I'd be interested to know how you overcame the configuration changes required to downgrade from v4.

Are you using Cloudflare C3 to scaffold a Nuxt or similar project?

Did you have the same problem I mentioned where the file referenced in `.wrangler\deploy\config.json` does not exist `({"configPath":"..\\..\\dist\\_worker.js\\wrangler.json"}`?

**Comment by klipspringr** [comment]
@vy-ton any update on this?

**Comment by mrankine** [comment]
@vy-ton @lrapoport-cf any update on this?

**Comment by lakano** [comment]
Hi,
Sorry for my late feedback.

> Here's an import file which causes many HashIndex errors. Multiple INSERTs of the same values don't appear to trigger the error, at least in some quick testing.
> 
> [hash_errors.sql.txt](https://github.com/user-attachments/files/18945216/hash_errors.sql.txt)

Thank you for this .sql file, I got the same error with your hash_errors.sql file too, I suppose workers-sdk developers could uses to debug and fix this issue.

As reported when I've created this ticket, this bug occurred under wrangler 3.108.0 ( GNU/Linux Arch - kernel 6.13.8-zen1 )
I'v tried to go back to 3.103.2 and I can confirm this also solve this issue for me, for this hash_errors.sql file but also for my initial export.sql file. ( Thank you @mrankine to dig and found this previous wrangler version that works! )

If tried all the next releases, and it's works until 3.106.0 included, the next release available for public seems to be the 3.107.2 where the bug appear. But in the release details ( https://github.com/cloudflare/workers-sdk/releases/tag/wrangler%403.107.2 ) the only information is about a revert patch from the version 3.107, and this version wasn't published on npmjs. 

Then I've tried the last current release, 4.8.0 and the bug is still present but with an extra reference information : 
`✘ [ERROR] internal error; reference = vi5r7at8elidlhtfv1je6c75
`

Hope theses informations could help devs to fix this annoying bug.

**Comment by caprolactam** [comment]
Looks like this only happens with packages that depend on `miniflare >=3.20250129.0` (e.g. [`wrangler >=3.107.1`](https://github.com/cloudflare/workers-sdk/releases/tag/wrangler%403.107.1), [`@cloudflare/vitest-pool-workers >=0.6.10`](https://github.com/cloudflare/workers-sdk/releases/tag/%40cloudflare%2Fvitest-pool-workers%400.6.10)).

It is because [the following code](https://github.com/caprolactam/cf-hash-table-error) works with `miniflare@3.20250124.1`, but fails with `miniflare@3.20250129.0`.

Something probably went wrong in the code changes from `workerd@1.20250124.0` to `workerd@1.20250129.0`, as [noted here](https://github.com/cloudflare/workers-sdk/releases/tag/miniflare%403.20250129.0).

**Comment by mrankine** [comment]
Looking at the [changelog ](https://github.com/cloudflare/workerd/releases/tag/v1.20250129.0) for `workerd@v1.20250129.0`, [this commit](https://github.com/cloudflare/workerd/pull/3376) could be related to the hash errors we are seeing: `Use arm64/x86_64 ISA extensions to compute CRC32C` by @fhanau

**Comment by fhanau** [comment]
> Looking at the [changelog ](https://github.com/cloudflare/workerd/releases/tag/v1.20250129.0) for `workerd@v1.20250129.0`, [this commit](https://github.com/cloudflare/workerd/pull/3376) could be related to the hash errors we are seeing: `Use arm64/x86_64 ISA extensions to compute CRC32C` by [@fhanau](https://github.com/fhanau)

Is CRC32C being used in the given range of changes though? Support for it was only made available shortly before the commit and it is available through the `DigestStream` API, not sure if that is being used in the D1 API.

**Comment by f1ps1** [comment]
I'm also having this problem.
Running wrangler on an old version was a workaround for me:

```
npx wrangler@3.103.2 d1 execute mydb --local --file="./catalog/products.sql"
```

**Comment by vy-ton** [comment]
this is on our plan to address this quarter, hope to start in May

**Comment by brewaa** [comment]
Just want to add some more findings in the hope it might help.

I downgraded to:

```
"nitro-cloudflare-dev": "^0.1.5",
"wrangler": "^3.87.0"
```

I reset my database:

- Removed all tables
- Applied my initial migration

When I try to import a 41mb file using this command:

`npx wrangler d1 execute DBNAME --file .\tmp\export.sql --local`

I receive the error:

`kj/table.c++:103: warning: detected excessive collisions in hash table; is your hash function OK?; entryCount = 2897; collisionCount = 25405; kj::getStackTrace() = 7ff6160f0fb2 7ff61690162c 7ff6168fd698 7ff616901294 7ff6161b4a5e 7ff615eb3a00 7ff615eb3763 7ff615eb355a 7ff6177a4579 7ff6777d4152 31b00000068 31b00a57494 9 31b00000790 31b11ac8278 624e 31b123ca2bc 31b123ca45c 31b123ca4e0`

**But the data is actually imported successfully.**


I tested the same process again. Reset the database and attempt the execute from file using these versions:

```
"nitro-cloudflare-dev": "^0.2.2",
"wrangler": "^4.14.1"
```

The error output from wrangler@4.14.1 is much more verbose so I'm just posting a few lines of which there were hundreds:

```
kj/table.c++:57: error: HashIndex detected hash table inconsistency. This can happen if you create a kj::Table with a hash index and you modify the rows in the table post-indexing in a way that would change their hash. This is a serious bug which will lead to undefined behavior.
stack: ; kj::getStackTrace() = 7ff644e15a07 7ff6451cc791 7ff6451c78df 7ff6451cb014 7ff6449b3d3e 7ff64488bf60 7ff64488bcc4 7ff64488baba 7ff645e00339 7ff6a5e49061 c900000010 c900a97340 9 c900000760 c919a63094
kj/table.c++:57: error: HashIndex detected hash table inconsistency. This can happen if you create a kj::Table with a hash index and you modify the rows in the table post-indexing in a way that would change their hash. This is a serious bug which will lead to undefined behavior.
stack: ; kj::getStackTrace() = 7ff644e15a07 7ff6451cc806 7ff6451c78df 7ff6451cb014 7ff6449b3d3e 7ff64488bf60 7ff64488bcc4 7ff64488baba 7ff645e00339 7ff6a5e49061 c900000010 c900a97340 9 c900000760 c919a63094
kj/table.c++:57: error: HashIndex detected hash table inconsistency. This can happen if you create a kj::Table with a hash index and you modify the rows in the table post-indexing in a way that would change their hash. This is a serious bug which will lead to undefined behavior.
```

**But the data import was unsuccessful.**

I then downgraded to:

```
"nitro-cloudflare-dev": "^0.2.2",
"wrangler": "^3.87.0"
```

Despite the error:
`kj/table.c++:103: warning: detected excessive collisions in hash table; is your hash function OK?; entryCount = 2897; collisionCount = 25405; kj::getStackTrace() = 7ff642ea0fb2 7ff6436b162c 7ff6436ad698 7ff6436b1294 7ff642f64a5e 7ff642c63a00 7ff642c63763 7ff642c6355a 7ff644554579 7ff6a455a7d2 33600000068 33600a57494 9 33600000790 336118e8ab8 624e 33612326114 336123262b4 33612326338`

**The data is imported successfully.**

I still receive the error with wrangler@3.87.0 but data is still inserted correctly.

Just to be sure I uninstalled wrangler@3.87.0 and upgraded to wrangler@3.105.1, reset the database again and the import worked successfully without error?!

These are my devDependencies:

```
"devDependencies": {
		"@cloudflare/workers-types": "^4.20250506.0",
		"nitro-cloudflare-dev": "^0.2.2",
		"nitropack": "^2.11.11",
		"wrangler": "^3.105.1"
	}
```


Hope that helps.

**Comment by jedidja** [comment]
> this is on our plan to address this quarter, hope to start in May

Awesome! I'm also experiencing this.

**Comment by lakano** [comment]
> this is on our plan to address this quarter, hope to start in May

Hi @vy-ton 
Can you share any new ETA about this issue please?

**Comment by mrankine** [comment]
Yes, I am also hitting this error in local development when trying to `exec` larger SQL statements using the Workers D1 binding. So it's not just `wrangler execute` that's affected.

@vy-ton @petebacondarwin  is there any update on this?

```
[0] kj/table.c++:57: error: HashIndex detected hash table inconsistency. This can happen if you create a kj::Table with a hash index and you modify the rows in the table post-indexing in a way that would change their hash. This is a serious bug which will lead to undefined behavior.
...
[0] *** Received signal #11: Segmentation fault
[0] stack: /home/[..]/node_modules/.pnpm/@cloudflare+workerd-linux-64@1.20251011.0/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2d1978f /home/foo/node_modules/.pnpm/@cloudflare+workerd-linux-64@1.20251011.0/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2d14466 /home/foo/node_modules/.pnpm/@cloudflare+workerd-linux-64@1.20251011.0/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2d18a28 /home/foo/node_modules/.pnpm/@cloudflare+workerd-linux-64@1.20251011.0/node_modules/@cloudflare/workerd-linux-64/bin/workerd@1f771e2 /home/foo/node_modules/.pnpm/@cloudflare+workerd-linux-64@1.20251011.0/node_modules/@cloudflare/workerd-linux-64/bin/workerd@371a0be /home/foo/node_modules/.pnpm/@cloudflare+workerd-linux-64@1.20251011.0/node_modules/@cloudflare/workerd-linux-64/bin/workerd@3719d90 /home/foo/node_modules/.pnpm/@cloudflare+workerd-linux-64@1.20251011.0/node_modules/@cloudflare/workerd-linux-64/bin/workerd@3584875
```

**Comment by taojoe** [comment]
In the testing environment, this issue can be temporarily resolved by importing SQL using the `sqlite` command.

**Comment by treeder** [comment]
This is still an issue.  You can use this instead though in the meantime (I'm surprised it's not using this under the hood?):

```sh
sqlite3 .wrangler/state/v3/d1/miniflare-D1DatabaseObject/43f2xxxbbc25.sqlite < ./db.sql
```
