### ISSUE TITLE
vite plugin multi workers with dev-registry

### ISSUE THREAD

**Issue by cloudkite** [cloudflare/workers-sdk#8963]
### Describe the solution

Currently using wrangler dev you can run multiple workers by running a separate `wrangler dev` command for each worker and they can still interact with each other via RPC and fetch. I believe internally this is called the dev-registry.

This does not seem to be supported when using the @cloudflare/vite-plugin. It seems the suggestion is to use auxiliaryWorkers https://github.com/cloudflare/workers-sdk/blob/main/packages/vite-plugin-cloudflare/playground/multi-worker/vite.config.ts

However there are some limitations with this approach namely:

- auxiliaryWorkers do not support routes. I want to RPC between workers A & B, but both of those workers also have their own routes which they can respond to and also may have different asset bindings. Using auxiliaryWorkers only one of those workers can have routes.
- Cannot have multiple vite.config.ts. I want to be able to have seperate vite.config.ts for each worker. For example if one of my workers is a react-router worker and another is a svelte or plain react worker then I can't support this configuration with a single vite.config.ts and auxiliaryWorkers.

without support for dev-registry in the vite-plugin its very hard to mimic a production multi worker setup in your local dev environment.

Would be awesome to be able to run a seperate `vite dev` for each worker and still have them talk to each other via RPC and fetch.

**Comment by franciscohermida** [comment]
This would be awesome to have 🙏

**Comment by hkochniss** [comment]
Can you explain the specific usecase of "2 Service-binding-connected" workers that are both available through separate routes? I think it would be helpful to understand the impact, and also I'm intrigued if I missed out on some architectural opportunities

**Comment by cloudkite** [comment]
> Can you explain the specific usecase of "2 Service-binding-connected" workers that are both available through separate routes? I think it would be helpful to understand the impact, and also I'm intrigued if I missed out on some architectural opportunities

I have different workers bound to different subpaths. For example one worker handles all requests to /files/* and another handles /embed/* etc then a "main" worker that handles all other paths. This helps keep bundle size down while still being able to communicate via RPC between those workers.

**Comment by catman8s** [comment]
I may I found a solution to your problem. Check it out here [click](https://javierlopez.eu/captha/)

**Comment by hkochniss** [comment]
Ok thanks, that means in your case you use RPC for basically code/logic re-use, as you could also bundle the shared functionality into a lib and reuse it that way.. saving some kbyte per worker.. 

Wonder if there are cases where this is more needed or even absolutely neccessary

**Comment by cloudkite** [comment]
> Ok thanks, that means in your case you use RPC for basically code/logic re-use, as you could also bundle the shared functionality into a lib and reuse it that way.. saving some kbyte per worker.. (still not sure what you do in RPC that is shared between static files and embeds, but maybe there is some datafetching or auth logic)
> 
> Wonder if there are cases where this is more needed or even absolutely necessary or unergonomic otherwise

If you have workers in different frameworks or languages that would be a scenario where it’s impossible todo any other way.

**Comment by jamesopstad** [comment]
Thanks for making the case for this. We'll be working soon on adding support for the DevRegistry in the Vite plugin.

**Comment by jamesopstad** [comment]
> Another use case for this is if you are making RPC calls that can then make additional RPC calls. I have Worker A using React Router v7 + Vite making RPC calls inside actions to Worker B which makes calls to Worker C and Worker D. Even after adding all to auxiliaryWorkers it still does not work.

@mgandolfi7 Please can you open a separate issue with a reproduction. This should work in development so if it doesn't it's a bug.

We don't officially support `auxiliaryWorkers` with React Router yet because they aren't included at build time but there is a feature coming soon to Vite that will make this possible.

**Comment by edmundhung** [comment]
We've just added dev registry support to the `@cloudflare/vite-plugin` in version 1.4.0—see the [release notes](https://github.com/cloudflare/workers-sdk/releases/tag/%40cloudflare%2Fvite-plugin%401.4.0) for details. Feel free to try it out and let us know if you encounter any issues or have ideas for further improvements. Thank you!

**Comment by kotkoroid** [comment]
@edmundhung Hi, thank you for the dev registry support. I'm trying to set it up but I encounter issues. First, I would like to confirm that the feature allows me to remove `auxiliaryWorkers` and `persistState` keys from the Cloudflare plugin configuration in Vite configuration, which was recommended [here](https://github.com/cloudflare/workers-sdk/issues/8899), is that correct?

**Comment by vnphanquang** [comment]
Hi all, thank you for the good work. 

I'm trying to implement an RPC setup via service binding between a Sveltekit app (with Cloudflare adapter) and a separate worker using the vite plugin, but couldn't connect them when using `vite dev` for the worker. Instead I had to start the worker using `wrangler dev` for it to be found by the SvelteKit app. Not sure if this is related to the dev-registry work in this issue; if not i'm happy to create a separate one.

Here is the reproduction: https://github.com/vnphanquang/reproduction-vite-sveltekit-cloudflare-service-binding

I believe SvelteKit uses [getPlatformProxy](https://developers.cloudflare.com/workers/wrangler/api/#getplatformproxy). Happy to bring this up to the SvelteKit team if you think they need to get involved.

Thanks!

**Comment by astanciu** [comment]
I'm also running into a problem with vite dev and service binding to, and from, other workers. 
Here is a repo with a simple repro, of both scenarios (vite dev worker is both the caller and callee) 
https://github.com/astanciu/cf_worker_repro

**Comment by edmundhung** [comment]
Thanks for the repro @vnphanquang! I've identified the issue and submitted a fix (#9508). I'll update here once it's released.

@astanciu Your repro should partly work once the fix above lands—the dash service will start receiving requests, but there's another issue preventing static assets from being served. I'm currently working on a fix for that.

**Comment by cloudkite** [comment]
@edmundhung finally got around to trying this on our non-trivial react-router app and worked first try. Thanks so much for your work on this

**Comment by edmundhung** [comment]
The fix has been released in @cloudflare/vite-plugin@1.5.1.

We're still working on the static asset issue—there's an open PR for it (#9556), but it will take a bit more time since it depends on additional changes in the runtime. I will post an update once it's ready.

**Comment by astanciu** [comment]
@edmundhung please see my reproduction repo above, both issues i brought up still exist. I just tried it with wrangler 4.20.0 and cloudflare-vite-plugin 1.6.0

**Comment by niba** [comment]
It also doesn't work in my codebase. As a workaround, you can call this code before `defineConfig` in `vite.config`

```typescript
process.env.MINIFLARE_REGISTRY_PATH = path.join(
	os.homedir(),
	".config/.wrangler/registry/",
);
```

Then the vite worker connects to the wrangler workers

**Comment by edmundhung** [comment]
@astanciu I had a look at your repo earlier today. Issue 1 should be resolved with v1.5.1, as long as you remove the service binding from your Wrangler config (which is tied to issue 2). That second issue will be addressed by #9583.
