### ISSUE TITLE
filename.replace is not a function error when using @cloudflare/vite-plugin with SSR

### ISSUE THREAD

**Issue by BeiXiao** [cloudflare/workers-sdk#9036]
### Which Cloudflare product(s) does this pertain to?

Vite Plugin

### What versions & operating system are you using?

^1.0.8

### Describe the Bug

`filename.replace is not a function` error when using @cloudflare/vite-plugin with SSR

Environment:
- @cloudflare/vite-plugin (latest)
- @react-router v7
- vite v6

Using SSR build with  `cloudflare({ viteEnvironment: { name: "ssr" } }),`

Error Description:
When configuring @cloudflare/vite-plugin with viteEnvironment: { name: "ssr" } in vite.config.ts, the build fails with the following error:
```
filename.replace is not a function
   at async ProxyServer.fetch (file:///.../node_modules/.pnpm/miniflare@4.20250417.0/node_modules/miniflare/src/workers/core/proxy.worker.ts:173:11)
The error disappears when removing the viteEnvironment configuration.
```
Reproduction Steps:

Use the following configuration:
``` 
import { cloudflare } from "@cloudflare/vite-plugin";
import { reactRouter } from "@react-router/dev/vite";
import { defineConfig } from "vite";
import macrosPlugin from "vite-plugin-babel-macros";
import tsconfigPaths from "vite-tsconfig-paths";
import { lingui } from "@lingui/vite-plugin";

export default defineConfig(({ isSsrBuild }) => ({
  resolve: {
    alias: {
      "~": "/app",
    },
  },
  plugins: [
    macrosPlugin(),
    cloudflare({ viteEnvironment: { name: "ssr" } }), // Error occurs with this line
    reactRouter(),
    tsconfigPaths(),
    lingui({
      configPath: './lingui.config.ts',
    }),
  ],
  ssr: {
    noExternal: [
      "@udecode/plate-math",
      // ... other packages
    ]},
}));
```
Run the build with SSR enabled

Expected Behavior:
The build should complete successfully with SSR support enabled through viteEnvironment: { name: "ssr" }.

Actual Behavior:
Build fails with filename.replace is not a function error.

Additional Information:

The error appears to originate from miniflare's proxy worker

The issue is reproducible consistently with this configuration

Removing viteEnvironment configuration makes the error disappear, but we need SSR functionality

Workaround:
Currently, the only workaround is to remove the viteEnvironment configuration, which disables the needed SSR functionality.

Would appreciate any guidance on how to properly configure SSR with this setup. Thank you!

**Comment by Amateur0x1** [comment]
I encountered the same error.

**Comment by jamesopstad** [comment]
Removing the `ssr.noExternal` entry in the Vite config should resolve the issue. Are you able to confirm? It's not necessary as we have `resolve.noExternal` set to `true` in the Cloudflare plugin.

I think the cause of the bug is actually in Vite because of the way it merges the legacy `ssr` config field with the new environments config. This results in this array - `['@udecode/plate-math', true]` - and then it tries to call `true.replace`, which fails. I'll have a look at the Vite code and see if this can be improved.

**Comment by jamesopstad** [comment]
This should be fixed in https://github.com/vitejs/vite/pull/20077. I'll confirm when that is released.

**Comment by j4crev** [comment]
@jamesopstad I'm on vite 7.0.4 and this is still an issue for me, unless I also comment out `ssr: { noExternal: ['<package>'] }` in my own vite plugin.

However, even with commenting it out, though things work in vite dev mode, it's failing to build; I suspect because said "package" is no longer listed in `noExternal`.

**Comment by sergiocarneiro** [comment]
Hopefully this gets fixed soon, can't use my UI library containing [stylex](https://stylexjs.com) without including it in `noExternal`.

Is there a workaround for this?

**Comment by jamesopstad** [comment]
> This should be fixed in [vitejs/vite#20077](https://github.com/vitejs/vite/pull/20077). I'll confirm when that is released.

It looks like this PR didn't fix the issue as the `ssr.noExternal` option is still incorrectly merged with `environments.ssr.resolve.noExternal`. I'll open an issue in the Vite repo. I recommend using `environments.ssr` to configure the `ssr` environment  rather than the legacy `ssr` option though.

@j4w8n and @sergiocarneiro The value of `noExternal` set by the plugin is `true`, meaning that no packages are externalised. Please could you open separate issues with reproductions as the issues you're facing sound a little different. Thanks!

**Comment by jamesopstad** [comment]
I've opened an issue in the Vite repo - https://github.com/vitejs/vite/issues/20499.

**Comment by j4crev** [comment]
> > This should be fixed in [vitejs/vite#20077](https://github.com/vitejs/vite/pull/20077). I'll confirm when that is released.
> 
> It looks like this PR didn't fix the issue as the `ssr.noExternal` option is still incorrectly merged with `environments.ssr.resolve.noExternal`. I'll open an issue in the Vite repo. I recommend using `environments.ssr` to configure the `ssr` environment rather than the legacy `ssr` option though.
> 
> [@j4w8n](https://github.com/j4w8n) and [@sergiocarneiro](https://github.com/sergiocarneiro) The value of `noExternal` set by the plugin is `true`, meaning that no packages are externalised. Please could you open separate issues with reproductions as the issues you're facing sound a little different. Thanks!

I can confirm that using `environments.ssr.resolve.noExternal` resolved my issue. Thanks!

**Comment by tv42** [comment]
Interestingly, this breaks vitest tests in a project using SvelteKit *if* using vitest `environment: "node"` or `environment: "edge-runtime"`, but not tests with `environment: "happy-dom"`.

```
 FAIL   server  src/demo.test.ts [ src/demo.test.ts ]
TypeError: filename.replace is not a function
  Plugin: vite:import-analysis
  File: /blah/src/demo.test.ts
 ❯ normalizePath$5 node_modules/vite/dist/node/chunks/dep-BHkUv4Z8.js:1847:18
 ❯ getMatcherString$1 node_modules/vite/dist/node/chunks/dep-BHkUv4Z8.js:1850:82
 ❯ Object.test node_modules/vite/dist/node/chunks/dep-BHkUv4Z8.js:1857:19
 ❯ result node_modules/vite/dist/node/chunks/dep-BHkUv4Z8.js:1872:16
 ❯ node_modules/vite/dist/node/chunks/dep-BHkUv4Z8.js:11792:28
 ❯ node_modules/vite/dist/node/chunks/dep-BHkUv4Z8.js:11802:115
 ❯ shouldExternalize node_modules/vite/dist/node/chunks/dep-BHkUv4Z8.js:11759:9
 ❯ node_modules/vite/dist/node/chunks/dep-BHkUv4Z8.js:30052:11
 ❯ TransformPluginContext.transform node_modules/vite/dist/node/chunks/dep-BHkUv4Z8.js:30025:30
```

SvelteKit's vite plugin uses `ssr: noExternal`:

```javascript
				ssr: {
					noExternal: [
						// This ensures that esm-env is inlined into the server output with the
						// export conditions resolved correctly through Vite. This prevents adapters
						// that bundle later on from resolving the export conditions incorrectly
						// and for example include browser-only code in the server output
						// because they for example use esbuild.build with `platform: 'browser'`
						'esm-env',
						// This forces `$app/*` modules to be bundled, since they depend on
						// virtual modules like `__sveltekit/paths` (this isn't a valid bare
						// import, but it works with vite-node's externalization logic, which
						// uses basic concatenation)
						'@sveltejs/kit/src/runtime'
					]
				}
```

**Comment by jamesopstad** [comment]
Closing as this was fixed in https://github.com/vitejs/vite/pull/20502 and released in Vite v7.1.0.
